### ISSUE TITLE
Unable to build image using mda file

### ISSUE THREAD

**Issue by vijayakumar-t** [mendix/docker-mendix-buildpack#107]
Hi,
I am able to build image by copy entire project folder into buildpack folder. But i am not able to build image using .mda file . In detail, 
1. Created .mda file from Mendix pro
2. Created one project folder under Mendix-buildpack folder
3. Copied and paste that mda file into project folder under mendix-buildpack 
4. Run build command from cmd, its executing commands one by one from Dockerfile finally throws an error as "Exception: No model/metadata.json or .mpr found in archive"

Is there possibility to build image from mda file or not. Please clarify my doubt.

=======================
This is the error i am facing
=======================
Traceback (most recent call last):
  File "/opt/mendix/buildpack/buildpack/runtime.py", line 89, in get_version
    with open(file_name) as file_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/mendix/build/model/metadata.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mendix/buildpack/buildpack/compile.py", line 141, in <module>
    preflight_check()
  File "/opt/mendix/buildpack/buildpack/compile.py", line 63, in preflight_check
    mx_version_str = runtime.get_version(BUILD_DIR)
  File "/opt/mendix/buildpack/buildpack/runtime.py", line 95, in get_version
    raise Exception("No model/metadata.json or .mpr found in archive")
Exception: No model/metadata.json or .mpr found in archive
Traceback (most recent call last):
  File "./compilation", line 66, in <module>
    exit_code = call_buildpack_compilation()
  File "./compilation", line 37, in call_buildpack_compilation
    return subprocess.check_call(["/opt/mendix/buildpack/buildpack/compile.py", BUILD_PATH, CACHE_PATH])
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/mendix/buildpack/buildpack/compile.py', '/opt/mendix/build', '/tmp/buildcache']' returned non-zero exit status 1.
The command '/bin/sh -c mkdir -p /tmp/buildcache /var/mendix/build /var/mendix/build/.local &&    chmod +rx /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git /opt/mendix/buildpack/buildpack/compile.py &&    cd /opt/mendix/buildpack &&    ./compilation /opt/mendix/build /tmp/buildcache &&    rm -fr /tmp/buildcache /tmp/javasdk /tmp/opt /tmp/downloads /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git &&    ln -s /opt/mendix/.java /opt/mendix/build &&    chgrp -R 0 /opt/mendix /var/mendix &&    chmod -R g=u /opt/mendix /var/mendix' returned a non-zero code: 1

**Comment by MXClyde** [comment]
From the documentation:

BUILD_PATH indicates where the application model is located. It is a root directory of an **unzipped** .MDA or .MPK file. In the latter case, this is the directory where your .MPR file is located. Must be within build context. Defaults to ./project.

With emphasis on unzipped ;-)

**Comment by vijayakumar-t** [comment]
Hi .
Thanks for the quick reply. 
In Dockerfile mentioned like create image by source code or mda file.  Please have a look at following 2 cases
case 1:
![image](https://user-images.githubusercontent.com/66428688/99681296-fc8bfa80-2aa3-11eb-9d14-04e6f41055bf.png)
In this case1 when i am trying to build it is working

case 2:
![image](https://user-images.githubusercontent.com/66428688/99681503-352bd400-2aa4-11eb-8932-317f89a6f0cc.png)
In this case2 i am not able to run command successfully.

This is the screenshot of Docker file
![image](https://user-images.githubusercontent.com/66428688/99680882-89828400-2aa3-11eb-976b-6dfc60939494.png)

Please clarify me whether we build from mda file or not. 

Thanks.

**Comment by MXClyde** [comment]
As documented, you have to unzip the .MDA file into a subdirectory of the buildpack (e.g. using winzip or something) . Then you can build from that as well.

**Comment by vijayakumar-t** [comment]
Now its clear to me .Thanks for the quick support .

**Comment by parulmishra20** [comment]
I have the same issue.. Please help here
