### ISSUE TITLE
Buildpack 3.4.0 with cf buildpack version 4.20.0 - Error 

### ISSUE THREAD

**Issue by tejaswi33** [mendix/docker-mendix-buildpack#130]
Hello everyone , 

I'm trying to build a docker image of my Mendix app ( Version 9.6 ) , recently migrated from 9.4 . I have the below error 

 ERROR: Starting application failed. Traceback (most recent call last):
aero-app-mendix_dev_1  |   File "/opt/mendix/buildpack/buildpack/start.py", line 161, in <module>
aero-app-mendix_dev_1  |     nginx.configure(m2ee)
aero-app-mendix_dev_1  |   File "/opt/mendix/buildpack/buildpack/nginx.py", line 111, in configure
aero-app-mendix_dev_1  |     locations=_get_locations(),
aero-app-mendix_dev_1  |   File "/opt/mendix/buildpack/buildpack/nginx.py", line 313, in _get_locations
aero-app-mendix_dev_1  |     rest_handler_paths = runtime.get_rest_request_handler_paths()
aero-app-mendix_dev_1  |   File "/opt/mendix/buildpack/buildpack/runtime.py", line 164, in get_rest_request_handler_paths
aero-app-mendix_dev_1  |     stderr=subprocess.STDOUT,
aero-app-mendix_dev_1  |   File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
aero-app-mendix_dev_1  |     **kwargs).stdout
aero-app-mendix_dev_1  |   File "/usr/lib64/python3.6/subprocess.py", line 423, in run
aero-app-mendix_dev_1  |     with Popen(*popenargs, **kwargs) as process:
aero-app-mendix_dev_1  |   File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
aero-app-mendix_dev_1  |     restore_signals, start_new_session)
aero-app-mendix_dev_1  |   File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
aero-app-mendix_dev_1  |     raise child_exception_type(errno_num, err_msg, err_filename)
aero-app-mendix_dev_1  | FileNotFoundError: [Errno 2] No such file or directory: 'strings': 'strings'

you help is much appreciated .

Regards
KC
![Docker-Image_error](https://user-images.githubusercontent.com/42318264/137128698-daa95b01-c37a-4210-9a36-e37784775b06.PNG)

**Comment by eddideku** [comment]
Working on a project this morning, I received an error during the build process:

`ModuleNotFoundError: No module named 'buildpack.core'`

I realized I'm just cloning the master branch. So their last commit broke my build process.

Were you able to resolve your issue? I am using 4.20.0
