### ISSUE TITLE
not able to build docker image on windows

### ISSUE THREAD

**Issue by parulmishra20** [mendix/docker-mendix-buildpack#144]
#17 sha256:d9d5889ef0659d11a043380e1e9b18fec24d4ca7b8e3652c8acc69ae64298c3b                                                                                                  #17 1.571 INFO: Mendix project compilation phase...                                                                                                                          #17 2.246 WARNING: Cannot retrieve metadata key RuntimeVersion                                                                                                               #17 2.247 Traceback (most recent call last):                                                                                                                                 #17 2.247   File "/opt/mendix/buildpack/buildpack/stage.py", line 132, in                                                                                            #17 2.247     runtime_version = runtime.get_runtime_version(BUILD_DIR)                                                                                                       #17 2.247   File "/opt/mendix/buildpack/buildpack/core/runtime.py", line 148, in get_runtime_version                                                                         #17 2.247     raise Exception("No model/metadata.json or .mpr found in archive")                                                                                             ### **#17 2.247 Exception: No model/metadata.json or .mpr found in archive                                                                                                         #17 2.314 Traceback (most recent call last):**                                                                                                                                 #17 2.314   File "./compilation", line 66, in                                                                                                                        #17 2.314     exit_code = call_buildpack_compilation()                                                                                                                       #17 2.314   File "./compilation", line 38, in call_buildpack_compilation                                                                                                     #17 2.314     return subprocess.check_call(["/opt/mendix/buildpack/buildpack/stage.py", BUILD_PATH, CACHE_PATH])                                                             #17 2.314   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call                                                                                                 #17 2.314     raise CalledProcessError(retcode, cmd)                                                                                                                         #17 2.314 subprocess.CalledProcessError: Command '['/opt/mendix/buildpack/buildpack/stage.py', '/opt/mendix/build', '/tmp/buildcache']' returned non-zero exit status 1.     #17 ERROR: executor failed running [/bin/sh -c mkdir -p /tmp/buildcache /var/mendix/build /var/mendix/build/.local &&    chmod +rx /opt/mendix/buildpack/compilation /opt/me ndix/buildpack/git /opt/mendix/buildpack/buildpack/stage.py &&    cd /opt/mendix/buildpack &&    ./compilation /opt/mendix/build /tmp/buildcache &&    rm -fr /tmp/buildcach e /tmp/javasdk /tmp/opt /tmp/downloads /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git &&    ln -s /opt/mendix/.java /opt/mendix/build &&    chown -R ${USER_UID }:0 /opt/mendix /var/mendix &&    chmod -R g=u /opt/mendix /var/mendix]: exit code: 1

**Comment by pphanpobe** [comment]
same to me
