### ISSUE TITLE
Build fails after v3.5.2

### ISSUE THREAD

**Issue by Jameswrstbnd** [mendix/docker-mendix-buildpack#150]
Build fails with this error after [v3.5.2](https://github.com/mendix/docker-mendix-buildpack/releases/tag/v3.5.2): 

```
#17 75.00 Traceback (most recent call last):
#17 75.00   File "./compilation", line 71, in <module>
#17 75.00     make_dependencies_reusable()
#17 75.00   File "./compilation", line 55, in make_dependencies_reusable
#17 75.00     jre = java._get_java_dependency(java.get_java_major_version(runtime.get_runtime_version(BUILD_PATH)), 'jre')
#17 75.00 AttributeError: module 'buildpack.core.java' has no attribute '_get_java_dependency'
------
error: failed to solve: executor failed running [/bin/sh -c mkdir -p /tmp/buildcache /tmp/cf-deps /var/mendix/build /var/mendix/build/.local &&    chmod +rx /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git /opt/mendix/buildpack/buildpack/stage.py &&    cd /opt/mendix/buildpack &&    ./compilation /opt/mendix/build /tmp/buildcache /tmp/cf-deps 0 &&    rm -fr /tmp/buildcache /tmp/javasdk /tmp/opt /tmp/downloads /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git &&    ln -s /opt/mendix/.java /opt/mendix/build &&    chown -R ${USER_UID}:0 /opt/mendix /var/mendix &&    chmod -R g=u /opt/mendix /var/mendix]: exit code: 1
Downloading files from /home/ubuntu/build to /...
```

**Comment by zlogic** [comment]
Could you please share details how you build the app?
Docker Buildpack depends on a specific version of CF Buildpack, [v4.30.2](https://github.com/mendix/docker-mendix-buildpack#compilation) in Docker Buildpack v3.5.2, and will not work with earlier versions of CF Buildpack.

**Comment by zlogic** [comment]
The automatd build/test suite was able to successfully build and run an app when Docker Buildpack v3.5.2 was released: https://github.com/mendix/docker-mendix-buildpack/actions/runs/2782227545

**Comment by Jameswrstbnd** [comment]
Figured it out, with your help. Thanks
