### ISSUE TITLE
make sure the compiltation failure are explicit during the docker build

### ISSUE THREAD

**Issue by RaphaelAudet** [mendix/docker-mendix-buildpack#16]

**Comment by MXClyde** [comment]
When build fails, the container does not return an error level. As a consequence, when used in a CI/CD pipeline there is no way to know the build has failed.
**To reproduce:** Build project with a deliberate error in the model

**Comment by JamesRamm** [comment]
Can this issue be made a priority? We often encounter an error in MxBuild which does not return an error code to the docker build process, resulting in a broken deployment.
At other times, network issues can cause problems since the build process contains downloads (e.g. of the mono runtime). If this fails for any reason, the build simply continues, resulting in a corrupted image.

Here is an example of the logs from a broken build from yesterday. We dont know what caused the error but you can see that it does not cause the docker build process to fail:

```
INFO: Selecting Mono Runtime: mono-5.20.1.27



   __  __      ____        _ _     _ 

  |  \/  |    |  _ \      (_) |   | |

  | \  / |_  _| |_) |_   _ _| | __| |

  | |\/| \ \/ /  _ <| | | | | |/ _` |

  | |  | |>  <| |_) | |_| | | | (_| |

  |_|  |_/_/\_\____/ \__,_|_|_|\__,_|



   v8.2.2.60770



ERROR: System.TypeInitializationException: The type initializer for 'Mendix.Modeler.WebUI.Forms.Widgets.LayoutWidgets.Tables.TableViewUtil' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.so.0

  at (wrapper managed-to-native) System.Drawing.GDIPlus.GdiplusStartup(ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)

  at System.Drawing.GDIPlus..cctor () [0x000b0] in <8113ed69c3044a87aa63ea677216ca14>:0 

   --- End of inner exception stack trace ---

  at System.Drawing.Image.InitFromStream (System.IO.Stream stream) [0x0006b] in <8113ed69c3044a87aa63ea677216ca14>:0 

  at System.Drawing.Bitmap..ctor (System.IO.Stream stream, System.Boolean useIcm) [0x00006] in <8113ed69c3044a87aa63ea677216ca14>:0 

  at System.Drawing.Bitmap..ctor (System.IO.Stream stream) [0x00000] in <8113ed69c3044a87aa63ea677216ca14>:0 

  at (wrapper remoting-invoke-with-check) System.Drawing.Bitmap..ctor(System.IO.Stream)

  at Mendix.Modeler.Theming.Icons.GetResourceValue (System.String resourceName, System.Func`2[T,TResult] iconConverter) [0x0000b] in <3bb53fd644b64b7baa8e164a91e4c174>:0 

  at Mendix.Modeler.Theming.Icons+<>c.<.cctor>b__7776_1315 () [0x00000] in <3bb53fd644b64b7baa8e164a91e4c174>:0 

  at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in <c5f248bd80f94e97ab8e6ff7becfb6f2>:0 

  at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in <c5f248bd80f94e97ab8e6ff7becfb6f2>:0 

  at System.Lazy`1[T].CreateValue () [0x00074] in <c5f248bd80f94e97ab8e6ff7becfb6f2>:0 

  at System.Lazy`1[T].get_Value () [0x0000a] in <c5f248bd80f94e97ab8e6ff7becfb6f2>:0 

  at Mendix.Modeler.Theming.Icons.get_MergeWithLeft () [0x00000] in <3bb53fd644b64b7baa8e164a91e4c174>:0 

  at Mendix.Modeler.WebUI.Forms.Widgets.LayoutWidgets.Tables.TableViewUtil..cctor () [0x00018] in <39ac16d2e61346b688dc5c7cfea08716>:0 

   --- End of inner exception stack trace ---

  at Mendix.Modeler.WebUI.Forms.Tasks.CommonTasks.Init () [0x0000a] in <39ac16d2e61346b688dc5c7cfea08716>:0 

  at Mendix.Modeler.WebUI.WebUIPlugin.Init () [0x00000] in <39ac16d2e61346b688dc5c7cfea08716>:0 

  at Mendix.Modeler.Plugins.PluginBase`1[TSelf].Mendix.Modeler.Plugins.IPlugin.Init (Mendix.Modeler.Core.IModelerCore _modelerCore) [0x00007] in <05e16ff7336741dabba93045ebb2b968>:0 

  at Mendix.Modeler.Plugins.PluginManager.Init (Mendix.Modeler.Core.IModelerCore modelerCore) [0x00014] in <05e16ff7336741dabba93045ebb2b968>:0 

  at Mendix.Modeler.ModelerCore.Init () [0x00029] in <05e16ff7336741dabba93045ebb2b968>:0 

  at Mendix.Modeler.ModelerCore.Create (Mendix.Modeler.Core.IProjectManager projectManager, Mendix.Modeler.Utility.IFileSystem fileSystem, Mendix.Modeler.Projects.Checks.IProjectChecker projectChecker, Mendix.Modeler.Plugins.IPluginManager pluginManager, System.Collections.Generic.IEnumerable`1[T] summaryProviders, System.Collections.Generic.IEnumerable`1[T] storageTypeConvertersProviders) [0x0000d] in <05e16ff7336741dabba93045ebb2b968>:0 

  at Mendix.CommandLine.Shared.ApplicationContainerFactory.InitializeModelerCore (Mendix.Modeler.Utility.DIContainer.IContainer container) [0x00024] in <590eb4eeb2284e7a96abe122dc71d27e>:0 

  at Mendix.CommandLine.Shared.ApplicationContainerFactory.Init (System.Action`1[T] overrides, System.Reflection.Assembly[] extraAssemblies) [0x00016] in <590eb4eeb2284e7a96abe122dc71d27e>:0 

  at Mendix.CommandLine.Shared.ApplicationContainerFactory.GetInstance (System.Action`1[T] overrides, System.Reflection.Assembly[] extraAssemblies) [0x00007] in <590eb4eeb2284e7a96abe122dc71d27e>:0 

  at Mendix.CommandLine.Shared.ApplicationContainerFactory.GetInstance (System.Reflection.Assembly[] extraAssemblies) [0x00000] in <590eb4eeb2284e7a96abe122dc71d27e>:0 

  at Mendix.CommandLine.Shared.ProgramHelper.InitializeAndRun[T] (System.Func`2[T,TResult] program, System.Reflection.Assembly[] extraAssemblies) [0x00005] in <590eb4eeb2284e7a96abe122dc71d27e>:0 



Unhandled Exception:

System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.so.0

  at (wrapper managed-to-native) System.Drawing.GDIPlus.GdiplusStartup(ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)

  at System.Drawing.GDIPlus..cctor () [0x000b0] in <8113ed69c3044a87aa63ea677216ca14>:0 

   --- End of inner exception stack trace ---

  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)

  at System.Drawing.Image.Dispose (System.Boolean disposing) [0x00000] in <8113ed69c3044a87aa63ea677216ca14>:0 

  at System.Drawing.Image.Finalize () [0x00000] in <8113ed69c3044a87aa63ea677216ca14>:0 

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.so.0

  at (wrapper managed-to-native) System.Drawing.GDIPlus.GdiplusStartup(ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)

  at System.Drawing.GDIPlus..cctor () [0x000b0] in <8113ed69c3044a87aa63ea677216ca14>:0 

   --- End of inner exception stack trace ---

  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)

  at System.Drawing.Image.Dispose (System.Boolean disposing) [0x00000] in <8113ed69c3044a87aa63ea677216ca14>:0 

  at System.Drawing.Image.Finalize () [0x00000] in <8113ed69c3044a87aa63ea677216ca14>:0 

ERROR: Could not read mxbuild error file

Traceback (most recent call last):

  File "/opt/mendix/buildpack/bin/../bin/compile.py", line 256, in run_mx_build

    subprocess.check_call(args, env=mono_env)

  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['/tmp/opt/mono-5.20.1.27/bin/mono', '--config', '/tmp/opt/mono-5.20.1.27/etc/mono/config', '/opt/mendix/build/.local/mxbuild/modeler/mxbuild.exe', '--target=package', '--output=/tmp/model.mda', '--java-home=/opt/mendix/build/.local/usr/lib/jvm/AdoptOpenJDK-jdk-11.0.3-AdoptOpenJDK-x64', '--java-exe-path=/opt/mendix/build/.local/usr/lib/jvm/AdoptOpenJDK-jdk-11.0.3-AdoptOpenJDK-x64/bin/java', '--write-errors=/tmp/builderrors.json', '/opt/mendix/build/amesim_webapp.mpr']' returned non-zero exit status 255.



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/opt/mendix/buildpack/bin/../bin/compile.py", line 294, in buildstatus_callback

    with codecs.open(error_file, "r", encoding="utf-8-sig") as b:

  File "/usr/lib/python3.6/codecs.py", line 897, in open

    file = builtins.open(filename, mode, buffering)

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/builderrors.json'

ERROR: MxBuild returned errors: {"problems": [{"severity": "Error", "message": "Failed to build the model, please check application logs for details.", "locations": []}]}

WARNING: No build status callback url set, so not going to submit the status

Traceback (most recent call last):

  File "/opt/mendix/buildpack/bin/../bin/compile.py", line 326, in <module>

    run_mx_build()

  File "/opt/mendix/buildpack/bin/../bin/compile.py", line 259, in run_mx_build

    raise e

  File "/opt/mendix/buildpack/bin/../bin/compile.py", line 256, in run_mx_build

    subprocess.check_call(args, env=mono_env)

  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['/tmp/opt/mono-5.20.1.27/bin/mono', '--config', '/tmp/opt/mono-5.20.1.27/etc/mono/config', '/opt/mendix/build/.local/mxbuild/modeler/mxbuild.exe', '--target=package', '--output=/tmp/model.mda', '--java-home=/opt/mendix/build/.local/usr/lib/jvm/AdoptOpenJDK-jdk-11.0.3-AdoptOpenJDK-x64', '--java-exe-path=/opt/mendix/build/.local/usr/lib/jvm/AdoptOpenJDK-jdk-11.0.3-AdoptOpenJDK-x64/bin/java', '--write-errors=/tmp/builderrors.json', '/opt/mendix/build/amesim_webapp.mpr']' returned non-zero exit status 255.

Removing intermediate container d556aa62a5c4

 ---> c651f9050756

Step 40/51 : RUN rm -fr /tmp/buildcache /tmp/javasdk /tmp/opt &&    ln -s /opt/mendix/.java /opt/mendix/build &&    chown -R mendix:root /opt/mendix &&    chmod -R g+rwX /opt/mendix

 ---> Running in 6b7ba7e4c2dc

Removing intermediate container 6b7ba7e4c2dc

 ---> 2466ce1d48cd

Step 41/51 : COPY --chown=mendix:root ${BUILDPACK_SRC}/scripts/startup /opt/mendix/build
```

**Comment by zlogic** [comment]
@JamesRamm We have identified an issue with building Mendix MPR projects in Ubuntu 18.04 and have reverted the base image to Ubuntu 14.04; the missing `libgdiplus.so.0` issue should be fixed now.
