### ISSUE TITLE
java.lang.Error: java.io.FileNotFoundException: /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-2.el8.x86_64/lib/tzdb.dat (No such file or directory)

### ISSUE THREAD

**Issue by eikstang** [mendix/docker-mendix-buildpack#176]
Hello all,

i have been building rootfs-app and rootfs-builder docker images to be 

docker build \
--build-arg BUILD_PATH=trunk \
--build-arg ROOTFS_IMAGE=$REPOSITORY_URI/mendix-rootfs:app \
--build-arg BUILDER_ROOTFS_IMAGE=$REPOSITORY_URI/mendix-rootfs:builder \
-t $REPOSITORY_URI/$ECS_SERVICE_NAME:$IMAGE_TAG .

which worked fine until today (when rootfs-app and rootfs-builder got updated).
they are being build by:
 build:
    commands:
      - wget https://github.com/mendix/docker-mendix-buildpack/archive/${DOCKER_MENDIX_BUILDPACK_VERSION}.zip && unzip ${DOCKER_MENDIX_BUILDPACK_VERSION}.zip
      - mv docker-mendix-buildpack-*/* . && rm -R docker-mendix-buildpack-*
      - docker build -t $REPOSITORY_URI/mendix-rootfs:app -f rootfs-app.dockerfile .
      - docker build -t $REPOSITORY_URI/mendix-rootfs:builder -f rootfs-builder.dockerfile .

now there seems to be an issue with javas tzdb.dat file as the actual mendix application docker image build runs into this error message during build phase:

2023-07-24T12:15:46
2023-07-24T12:15:46    __  __      ____        _ _     _
2023-07-24T12:15:46   |  \/  |    |  _ \      (_) |   | |
2023-07-24T12:15:46   | \  / |_  _| |_) |_   _ _| | __| |
2023-07-24T12:15:46   | |\/| \ \/ /  _ <| | | | | |/ _` |
2023-07-24T12:15:46   | |  | |>  <| |_) | |_| | | | (_| |
2023-07-24T12:15:46   |_|  |_/_/\_\____/ \__,_|_|_|\__,_|
2023-07-24T12:15:46
2023-07-24T12:15:46    v9.6.10.40529
2023-07-24T12:15:46
2023-07-24T12:15:54 Starting build for Mendix Project file: /opt/mendix/build/Program Supplier Asset Management.mpr
2023-07-24T12:15:54 Using the following options:
2023-07-24T12:15:54  * Build target: Package
2023-07-24T12:15:54  * Deployment package file: /tmp/model.mda
2023-07-24T12:15:54 Reading project file...
2023-07-24T12:16:14 Building project...
2023-07-24T12:16:14 Executing step 'Synchronize with file system'
2023-07-24T12:16:14  * Synchronizing with file system...
2023-07-24T12:16:14 Executing step 'Initialize'
2023-07-24T12:16:14  * Preparing deployment...
2023-07-24T12:16:14 Executing step 'Check prerequisites'
2023-07-24T12:16:14  * Checking for errors...
2023-07-24T12:16:24 Executing step 'Clean deployment directory'
2023-07-24T12:16:24  * Cleaning data broker files...
2023-07-24T12:16:24  * Cleaning deployment directory...
2023-07-24T12:16:24 ERROR: An error occurred while cleaning the deployment directory.
2023-07-24T12:16:24 Buildfile: /opt/mendix/build/deployment/build_core.xml
2023-07-24T12:16:24 Caught an exception while logging the end of the build.  Exception was:
2023-07-24T12:16:24 java.lang.NoClassDefFoundError: Could not initialize class sun.util.calendar.ZoneInfoFile
2023-07-24T12:16:24     at java.base/sun.util.calendar.ZoneInfo.getTimeZone(ZoneInfo.java:588)
2023-07-24T12:16:24     at java.base/java.util.TimeZone.getTimeZone(TimeZone.java:577)
2023-07-24T12:16:24     at java.base/java.util.TimeZone.setDefaultZone(TimeZone.java:682)
2023-07-24T12:16:24     at java.base/java.util.TimeZone.getDefaultRef(TimeZone.java:653)
2023-07-24T12:16:24     at java.base/java.util.TimeZone.getDefault(TimeZone.java:642)
2023-07-24T12:16:24     at java.base/java.util.Calendar.defaultTimeZone(Calendar.java:1679)
2023-07-24T12:16:24     at java.base/java.util.Calendar.getInstance(Calendar.java:1660)
2023-07-24T12:16:24     at java.base/java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:676)
2023-07-24T12:16:24     at java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:620)
2023-07-24T12:16:24     at org.apache.tools.ant.util.DateUtils.<clinit>(DateUtils.java:72)
2023-07-24T12:16:24     at org.apache.tools.ant.DefaultLogger.formatTime(DefaultLogger.java:304)
2023-07-24T12:16:24     at org.apache.tools.ant.DefaultLogger.buildFinished(DefaultLogger.java:175)
2023-07-24T12:16:24     at org.apache.tools.ant.Project.fireBuildFinished(Project.java:2089)
2023-07-24T12:16:24     at org.apache.tools.ant.Main.runBuild(Main.java:852)
2023-07-24T12:16:24     at org.apache.tools.ant.Main.startAnt(Main.java:223)
2023-07-24T12:16:24     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
2023-07-24T12:16:24     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
2023-07-24T12:16:24 There has been an error prior to that:
2023-07-24T12:16:24 java.lang.Error: java.io.FileNotFoundException: /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-2.el8.x86_64/lib/tzdb.dat (No such file or directory)
2023-07-24T12:16:24     at java.base/sun.util.calendar.ZoneInfoFile$1.run(ZoneInfoFile.java:261)
2023-07-24T12:16:24     at java.base/sun.util.calendar.ZoneInfoFile$1.run(ZoneInfoFile.java:251)
2023-07-24T12:16:24     at java.base/java.security.AccessController.doPrivileged(Native Method)
2023-07-24T12:16:24     at java.base/sun.util.calendar.ZoneInfoFile.<clinit>(ZoneInfoFile.java:251)

**Comment by eikstang** [comment]
seems to be caused by the change from java-11-openjdk-headless-1:11.0.19.0.7-4.el8.x86_64 to java-11-openjdk-11.0.20.0.8-2.el8.x86_64 as it still worked last friday when java-11-openjdk-headless was pointing to the previous version.

**Comment by eikstang** [comment]
this is more a RedHat ubi8 or java-11-openjdk packaging issue ....
