### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by terrorpup** [mendix/docker-mendix-buildpack#188]
I think I have the wrong brach 

=> ERROR [builder 6/6] RUN mkdir -p /tmp/buildcache /tmp/cf-deps /var/mendix/build /var/mendix/build/.local &&    chmod +rx /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git /opt/mendix/buildpack/buildpack/stage.py  5.6s
------
 > [builder 6/6] RUN mkdir -p /tmp/buildcache /tmp/cf-deps /var/mendix/build /var/mendix/build/.local &&    chmod +rx /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git /opt/mendix/buildpack/buildpack/stage.py &&    cd /opt
/mendix/buildpack &&    ./compilation /opt/mendix/build /tmp/buildcache /tmp/cf-deps 0 &&    rm -fr /tmp/buildcache /tmp/javasdk /tmp/opt /tmp/downloads /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git &&    ln -s /opt/me
ndix/.java /opt/mendix/build &&    chown -R 1001:0 /opt/mendix /var/mendix &&    chmod -R g=u /opt/mendix /var/mendix:
3.033 INFO: Mendix project compilation phase...
4.458 INFO: Preflight check on Mendix version [9.12.2.44241] and stack [None]...
4.458 INFO: Preflight check completed
4.459 INFO: Building from source...
4.460 INFO: Selecting Mono Runtime: 5
5.188 /opt/mendix/buildpack/buildpack/infrastructure/database.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release
 of cryptography (40.0) will be the last to support Python 3.6.
5.188   from cryptography.hazmat.primitives import serialization
5.298 Traceback (most recent call last):
5.298   File "/opt/mendix/buildpack/buildpack/core/mono.py", line 104, in ensure_and_get_mono
5.298     mono_location = _get_mono_path("/tmp/opt", version)
5.298   File "/opt/mendix/buildpack/buildpack/core/mono.py", line 45, in _get_mono_path
5.298     "Mono not found",
5.298   File "/opt/mendix/buildpack/buildpack/util.py", line 439, in get_existing_directory_or_raise
5.298     raise NotFoundException(error)
5.298 buildpack.util.NotFoundException: Mono not found
5.298
5.298 During handling of the above exception, another exception occurred:
5.298
5.298 Traceback (most recent call last):
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
5.298     chunked=chunked,
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
5.298     self._validate_conn(conn)
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
5.298     conn.connect()
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
5.298     tls_in_tls=tls_in_tls,
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
5.298     sock, context, tls_in_tls, server_hostname=server_hostname
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
5.298     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
5.298   File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
5.298     _context=self, _session=session)
5.298   File "/usr/lib/python3.6/ssl.py", line 817, in __init__
5.298     self.do_handshake()
5.298   File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
5.298     self._sslobj.do_handshake()
5.298   File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
5.298     self._sslobj.do_handshake()
5.298 OSError: [Errno 0] Error
5.298
5.298 During handling of the above exception, another exception occurred:
5.298
5.298 Traceback (most recent call last):
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
5.298     timeout=timeout
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
5.298     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/util/retry.py", line 532, in increment
5.298     raise six.reraise(type(error), error, _stacktrace)
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/packages/six.py", line 769, in reraise
5.298     raise value.with_traceback(tb)
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
5.298     chunked=chunked,
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
5.298     self._validate_conn(conn)
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
5.298     conn.connect()
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
5.298     tls_in_tls=tls_in_tls,
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
5.298     sock, context, tls_in_tls, server_hostname=server_hostname
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
5.298     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
5.298   File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
5.298     _context=self, _session=session)
5.298   File "/usr/lib/python3.6/ssl.py", line 817, in __init__
5.298     self.do_handshake()
5.298   File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
5.298     self._sslobj.do_handshake()
5.298   File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
5.298     self._sslobj.do_handshake()
5.298 urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))
5.298
5.298 During handling of the above exception, another exception occurred:
5.298
5.298 Traceback (most recent call last):
5.298   File "/opt/mendix/buildpack/buildpack/stage.py", line 195, in <module>
5.298     java_version,
5.298   File "/opt/mendix/buildpack/buildpack/core/mxbuild.py", line 27, in build_from_source
5.298     runtime_version, buildpack_path, cache_path
5.298   File "/opt/mendix/buildpack/buildpack/core/mono.py", line 112, in ensure_and_get_mono
5.298     unpack_strip_directories=True,
5.298   File "/opt/mendix/buildpack/buildpack/util.py", line 351, in resolve_dependency
5.298     download(url, cached_location)
5.298   File "/opt/mendix/buildpack/buildpack/util.py", line 426, in download
5.298     response = requests.get(url, stream=True)
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/requests/api.py", line 75, in get
5.298     return request('get', url, params=params, **kwargs)
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/requests/api.py", line 61, in request
5.298     return session.request(method=method, url=url, **kwargs)
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
5.298     resp = self.send(prep, **send_kwargs)
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
5.298     r = adapter.send(request, **kwargs)
5.298   File "/opt/mendix/buildpack/lib/python3.6/site-packages/requests/adapters.py", line 501, in send
5.298     raise ConnectionError(err, request=request)
5.298 requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))
5.403 /opt/mendix/buildpack/buildpack/infrastructure/database.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release
 of cryptography (40.0) will be the last to support Python 3.6.
5.403   from cryptography.hazmat.primitives import serialization
5.406 Traceback (most recent call last):
5.406   File "./compilation", line 67, in <module>
5.406     exit_code = call_buildpack_compilation()
5.406   File "./compilation", line 40, in call_buildpack_compilation
5.406     return subprocess.check_call(["/opt/mendix/buildpack/buildpack/stage.py", BUILD_PATH, CACHE_PATH, DEPS_DIR, DEPS_IDX])
5.406   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
5.406     raise CalledProcessError(retcode, cmd)
5.406 subprocess.CalledProcessError: Command '['/opt/mendix/buildpack/buildpack/stage.py', '/opt/mendix/build', '/tmp/buildcache', '/tmp/cf-deps', '0']' returned non-zero exit status 1.
------
Dockerfile:70
--------------------
  69 |     # 8. Update permissions of /opt/mendix so that the app can run as a non-root user
  70 | >>> RUN mkdir -p /tmp/buildcache /tmp/cf-deps /var/mendix/build /var/mendix/build/.local &&\
  71 | >>>     chmod +rx /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git /opt/mendix/buildpack/buildpack/stage.py &&\
  72 | >>>     cd /opt/mendix/buildpack &&\
  73 | >>>     ./compilation /opt/mendix/build /tmp/buildcache /tmp/cf-deps 0 &&\
  74 | >>>     rm -fr /tmp/buildcache /tmp/javasdk /tmp/opt /tmp/downloads /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git &&\
  75 | >>>     ln -s /opt/mendix/.java /opt/mendix/build &&\
  76 | >>>     chown -R ${USER_UID}:0 /opt/mendix /var/mendix &&\
  77 | >>>     chmod -R g=u /opt/mendix /var/mendix
  78 |
--------------------
ERROR: failed to solve: process "/bin/sh -c mkdir -p /tmp/buildcache /tmp/cf-deps /var/mendix/build /var/mendix/build/.local &&    chmod +rx /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git /opt/mendix/buildpack/buildpack
/stage.py &&    cd /opt/mendix/buildpack &&    ./compilation /opt/mendix/build /tmp/buildcache /tmp/cf-deps 0 &&    rm -fr /tmp/buildcache /tmp/javasdk /tmp/opt /tmp/downloads /opt/mendix/buildpack/compilation /opt/mendix/buildpack/
git &&    ln -s /opt/mendix/.java /opt/mendix/build &&    chown -R ${USER_UID}:0 /opt/mendix /var/mendix &&    chmod -R g=u /opt/mendix /var/mendix" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/default/default/sh6kfuowbgqa53rl5s8s15m4s

**Comment by anahitdshr** [comment]
Hi 
Any solution?

**Comment by zulfikar4568** [comment]
Hi, I have the same issue,
Any solution for this?
