### ISSUE TITLE
docker-mendix-buildpack v5.0.4 builds mendix 10.X but container startup throws unrecoverable error

### ISSUE THREAD

**Issue by mattmarich-wrstbnd** [mendix/docker-mendix-buildpack#191]
Hoping you can point me in the right direction or suggest a version of mendix 10 that we should be using:

```
ERROR - M2EE: An error occurred while initializing the Runtime: null
com.mendix.m2ee.api.AdminException: An error occurred while initializing the Runtime: null
        at com.mendix.basis.impl.MxRuntimeImplBase.start(MxRuntimeImplBase.java:255)

Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.mendix.container.support.EventProcessorDelegate.$anonfun$sendEvent$3(EventProcessorDelegate.scala:18)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at com.mendix.container.support.EventProcessorDelegate.sendEvent(EventProcessorDelegate.scala:16)
        at com.mendix.container.support.EventProcessor.sendEvent(EventProcessor.scala:23)
        at com.mendix.configuration.ConfigurationRegistry.handleUpdateConfig(ConfigurationRegistry.scala:61)
        at com.mendix.configuration.ConfigurationRegistry.handleInitConfig(ConfigurationRegistry.scala:80)
        at com.mendix.basis.impl.ProjectModelStoreLoaderImpl.load(ProjectModelStoreLoaderImpl.scala:32)
        at com.mendix.basis.impl.MxRuntimeImplBase.start(MxRuntimeImplBase.java:215)
        at com.mendix.m2ee.appcontainer.actions.StartAction.startRuntime(StartAction.scala:30)
        at com.mendix.m2ee.appcontainer.actions.StartAction.execute(StartAction.scala:17)
        at com.mendix.m2ee.appcontainer.server.handler.HttpAdminHandlerBase.service(HttpAdminHandlerBase.java:128)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
ERROR: Executing start did not succeed: result: 1, message: class com.mendix.m2ee.api.AdminException occurred while executing an admin action request. See logging output for details., caused by: class java.lang.reflect.InvocationTargetException occurred while executing an admin action request. See logging output for details.
WARNING: Unexpected result while starting app: 1.Please check your configuration for errors
ERROR: Starting application failed: Application start failed
INFO: Waiting for the application to shutdown...
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:829)

Caused by: com.mendix.metrics.MonitoringConfigurationError: Unable to initialize Metrics client: unsupported metric type: `statsd`.
        at com.mendix.metrics.MetricsImpl.createMetricsFactory(MetricsImpl.scala:63)
        at com.mendix.metrics.MetricsImpl.handleEvent(MetricsImpl.scala:37)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.mendix.container.support.EventProcessorDelegate.$anonfun$sendEvent$3(EventProcessorDelegate.scala:18)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at com.mendix.container.support.EventProcessorDelegate.sendEvent(EventProcessorDelegate.scala:16)
        at com.mendix.container.support.EventProcessor.sendEvent(EventProcessor.scala:23)
        at com.mendix.configuration.ConfigurationRegistry.handleUpdateConfig(ConfigurationRegistry.scala:61)
        at com.mendix.configuration.ConfigurationRegistry.handleInitConfig(ConfigurationRegistry.scala:80)
        at com.mendix.basis.impl.ProjectModelStoreLoaderImpl.load(ProjectModelStoreLoaderImpl.scala:32)
        at com.mendix.basis.impl.MxRuntimeImplBase.start(MxRuntimeImplBase.java:215)
        at com.mendix.m2ee.appcontainer.actions.StartAction.startRuntime(StartAction.scala:30)
        at com.mendix.m2ee.appcontainer.actions.StartAction.execute(StartAction.scala:17)
        at com.mendix.m2ee.appcontainer.server.handler.HttpAdminHandlerBase.service(HttpAdminHandlerBase.java:128)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:829)

INFO - M2EE: Runtime shutdown requested.
INFO - Core: Mendix Runtime is shutting down now...
[containersupport:eventing] WARNING: Could not send event because no event handler was found for topic `com/mendix/events/runtime/shutdown`.
INFO - Core: Mendix Runtime is now shut down.
INFO: The application has been stopped successfully.
```

**Comment by mattmarich-wrstbnd** [comment]
I was able to get pods to start by disabling datadog within the pods. I'm assuming its something within the datadog.py or run-datadog.sh script. I was initially thrown by the 'Unable to initialize Metrics client: unsupported metric type: `statsd`' error above since Mendix documentation states it's still included as a metric type. I haven't bothered de-compiling any of the jars to verify though.

**Comment by mattmarich-wrstbnd** [comment]
This was actually a cf-mendix-buildpack issue but can't open issue over there. To get datadog monitoring to work with Mendix 10 I used a commit from cf-mendix-buildback v5.0.13:
```
diff --git a//opt/mendix/buildpack/buildpack/telemetry/metrics.py b//opt/mendix/buildpack/buildpack/telemetry/metrics.py
index 9828a1a..709b370 100644
--- a//opt/mendix/buildpack/buildpack/telemetry/metrics.py
+++ b//opt/mendix/buildpack/buildpack/telemetry/metrics.py
@@ -108,9 +108,17 @@ def _micrometer_runtime_requirement(runtime_version):
 
 def micrometer_metrics_enabled(runtime_version):
     """Check for metrics from micrometer."""
-    return bool(get_micrometer_metrics_url()) and _micrometer_runtime_requirement(
-        runtime_version
-    )
+    logging.info("checking is micrometer metrics enabled")
+    micrometer_enabled=False
+    if(_micrometer_runtime_requirement(runtime_version)):
+        logging.debug("satisfies micrometer runtime requirement")
+        if(bool(get_micrometer_metrics_url())):
+            logging.debug("Found micrometer metrics url configured")
+            micrometer_enabled = True
+        elif(strtobool(os.getenv("NON_MENDIX_PUBLIC_CLOUD","false"))):
+            logging.debug("micrometer for non mendix public cloud")
+            micrometer_enabled =  True
+    return micrometer_enabled
 
 
 def configure_metrics_registry(m2ee):
```

Which then lead to telegraf errors which was resolved with:
```
diff --git a//opt/mendix/buildpack/etc/telegraf/telegraf.toml.j2 b//opt/mendix/buildpack/etc/telegraf/telegraf.toml.j2
index 5b4f04b..1c2bc17 100644
--- a//opt/mendix/buildpack/etc/telegraf/telegraf.toml.j2
+++ b//opt/mendix/buildpack/etc/telegraf/telegraf.toml.j2
@@ -378,81 +378,6 @@
   instance_index = "{{ cf_instance_index }}"
   app_name = "{{ app_name }}"
 
-[[outputs.http]]
-  alias = "mx-trends-metrics"
-
-  ## URL is the address to send metrics to
-  url = "{{ trends_storage_url }}"
-
-  ## Timeout for HTTP message
-  timeout = "10s"
-
-  ## HTTP method, one of: "POST" or "PUT"
-  method = "POST"
-
-  ## Data format to output.
-  data_format = "json"
-  json_timestamp_units = "1ns"
-
-  # tagexlude drops any non-relevant tags
-  tagexclude = ["host"]
-
-  # Drop `mx_runtime_user_login` metrics
-  # We drop them as we don't want it to be part of
-  # the payload which is used for Cloud graphs
-  namedrop = ["mx_runtime_user_login"]
-
-  ## Additional HTTP headers
-  [outputs.http.headers]
-  Content-Type = "application/json"
-  # custom header field
-  Micrometer-Metrics = "true"
-
-  # Pass only those metrics that has below tag set
-  [outputs.http.tagpass]
-  micrometer_metrics = ["true"]
-  internal_metrics = ["true"]
-
-[[outputs.http]]
-  alias = "datalake-metrics"
-
-  # This http output is ONLY to send all the datalake metrics
-  # as a single payload. For instance;
-  #  `mx_runtime_user_login`
-  namepass = ["mx_runtime_user_login"]
-
-  ## URL is the address to send metrics to
-  url = "{{ trends_storage_url }}"
-
-  ## Timeout for HTTP message
-  timeout = "10s"
-
-  # Higher flush interval and batch size, so that we
-  # don't bombard TFR and DataLake with too many requests, but
-  # few requests with bigger payloads
-  metric_batch_size = 2500
-  flush_interval = "30s"
-
-  ## HTTP method, one of: "POST" or "PUT"
-  method = "POST"
-
-  ## Data format to output.
-  data_format = "json"
-  json_timestamp_units = "1ns"
-
-  # include only relevant tags
-  taginclude = ["anonymous_upgrade", "user", "app_name", "instance_index"]
-
-  ## Additional HTTP headers
-  [outputs.http.headers]
-  Content-Type = "application/json"
-  # custom header field
-  Micrometer-Metrics = "true"
-
-  # Pass only those metrics that has below tag set
-  [outputs.http.tagpass]
-  micrometer_metrics = ["true"]
-
 {% if telegraf_fileout_enabled %}
 [[outputs.file]]
   ## Files to write to, "stdout" is a specially handled file.
```

Closing since I'm able to move on.
