### ISSUE TITLE
After running the application with the latest docker buildpack package, the following issues appear. PermissionError: [Errno 13] Permission denied: '/opt/mendix/build/../.java'

### ISSUE THREAD

**Issue by nikomao** [mendix/docker-mendix-buildpack#205]
##        .
                         ## ## ##       ==
                       ## ## ## ##      ===
                   /""""""""""""""""\___/ ===
              ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
                   \______ o          __/
                     \    \        __/
                      \____\______/

     __  __        _  _     _____             _
    |  \/  |      | || |   |  __ \           | |
    | \  / |_  __ | || |_  | |  | | ___   ___| | _____ _ __
    | |\/| \ \/ / |__   _| | |  | |/ _ \ / __| |/ / _ \ '__|
    | |  | |>  <     | |   | |__| | (_) | (__|   <  __/ |
    |_|  |_/_/\_\    |_|   |_____/ \___/ \___|_|\_\___|_|

                                digitalecosystems@mendix.com

    For a Kubernetes native solution to run Mendix apps,
    see Mendix for Private Cloud.

    
INFO: Executing export_industrial_edge_config_variable...
INFO: Mendix Cloud Foundry Buildpack v5.0.16 [e9a6e09] starting...
WARNING: CF_INSTANCE_INDEX environment variable not found, assuming cluster leader responsibility...
ERROR: Starting application failed. Traceback (most recent call last):
  File "/opt/mendix/build/buildpack/start.py", line 152, in <module>
    m2ee = runtime.setup(util.get_vcap_data())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mendix/build/buildpack/core/runtime.py", line 621, in setup
    _activate_license()
  File "/opt/mendix/build/buildpack/core/runtime.py", line 168, in _activate_license
    util.mkdir_p(prefs_dir)
  File "/opt/mendix/build/buildpack/util.py", line 377, in mkdir_p
    os.makedirs(path, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/opt/mendix/build/../.java'

**Comment by anahitdshr** [comment]
hi @nikomao any solution found ?
